"""Add auxiliary tables and link with IPER

Revision ID: 3151636a0370
Revises: 4cfba4376b07
Create Date: 2026-08-02 16:22:04.837564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3151636a0370'
down_revision = '4cfba4376b07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazard_catalogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iper_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=150), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('control_measures', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['hazard_id'], ['hazard_catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_iper_matrices_id'), table_name='iper_matrices')
    op.drop_index(op.f('ix_iper_matrices_project_name'), table_name='iper_matrices')
    op.drop_table('iper_matrices')
    op.drop_table('iper_matrix')
    op.drop_table('incidents')
    op.drop_table('personnel')
    op.drop_table('safety_talks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_talks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('talk_date', sa.TEXT(), nullable=False),
    sa.Column('topic', sa.TEXT(), nullable=False),
    sa.Column('project_name', sa.TEXT(), nullable=False),
    sa.Column('attendees', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.TEXT(), nullable=False),
    sa.Column('dni', sa.TEXT(), nullable=False),
    sa.Column('company', sa.TEXT(), nullable=False),
    sa.Column('medical_clearance', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('incident_date', sa.TEXT(), nullable=False),
    sa.Column('project_name', sa.TEXT(), nullable=False),
    sa.Column('injured_name', sa.TEXT(), nullable=False),
    sa.Column('person_type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('lost_days', sa.INTEGER(), nullable=False),
    sa.Column('severity_type', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iper_matrix',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_name', sa.TEXT(), nullable=False),
    sa.Column('hazard', sa.TEXT(), nullable=False),
    sa.Column('risk', sa.TEXT(), nullable=False),
    sa.Column('control_measure', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iper_matrices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(), nullable=False),
    sa.Column('hazard', sa.VARCHAR(), nullable=False),
    sa.Column('risk', sa.VARCHAR(), nullable=False),
    sa.Column('control_measure', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iper_matrices_project_name'), 'iper_matrices', ['project_name'], unique=False)
    op.create_index(op.f('ix_iper_matrices_id'), 'iper_matrices', ['id'], unique=False)
    op.drop_table('iper_records')
    op.drop_table('areas')
    op.drop_table('plants')
    op.drop_table('hazard_catalogs')
    # ### end Alembic commands ###