"""create iper matrix table

Revision ID: 4cfba4376b07
Revises: ccc828b85c8c
Create Date: 2026-08-02 12:43:29.648997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfba4376b07'
down_revision = 'ccc828b85c8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iper_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('hazard', sa.String(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('control_measure', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iper_matrices_id'), 'iper_matrices', ['id'], unique=False)
    op.create_index(op.f('ix_iper_matrices_project_name'), 'iper_matrices', ['project_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iper_matrices_project_name'), table_name='iper_matrices')
    op.drop_index(op.f('ix_iper_matrices_id'), table_name='iper_matrices')
    op.drop_table('iper_matrices')
    # ### end Alembic commands ###