"""add iper records and auxiliary tables

Revision ID: 6de5bcca9af5
Revises: 3151636a0370
Create Date: 2026-08-06 17:06:02.730217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de5bcca9af5'
down_revision = '3151636a0370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iper_matrix')
    op.drop_table('incidents')
    op.drop_table('personnel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.TEXT(), nullable=False),
    sa.Column('dni', sa.TEXT(), nullable=False),
    sa.Column('company', sa.TEXT(), nullable=False),
    sa.Column('medical_clearance', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('incident_date', sa.TEXT(), nullable=False),
    sa.Column('project_name', sa.TEXT(), nullable=False),
    sa.Column('injured_name', sa.TEXT(), nullable=False),
    sa.Column('person_type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('lost_days', sa.INTEGER(), nullable=False),
    sa.Column('severity_type', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iper_matrix',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_name', sa.TEXT(), nullable=False),
    sa.Column('hazard', sa.TEXT(), nullable=False),
    sa.Column('risk', sa.TEXT(), nullable=False),
    sa.Column('control_measure', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###