"""create personal table

Revision ID: ccc828b85c8c
Revises: 6604ad22bed8
Create Date: 2026-08-02 12:24:40.427157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc828b85c8c'
down_revision = '6604ad22bed8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apellido'), 'users', ['apellido'], unique=False)
    op.create_index(op.f('ix_users_dni'), 'users', ['dni'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nombre'), 'users', ['nombre'], unique=False)
    op.drop_index(op.f('ix_personal_apellido'), table_name='personal')
    op.drop_index(op.f('ix_personal_dni'), table_name='personal')
    op.drop_index(op.f('ix_personal_id'), table_name='personal')
    op.drop_index(op.f('ix_personal_nombre'), table_name='personal')
    op.drop_table('personal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('apellido', sa.VARCHAR(), nullable=True),
    sa.Column('dni', sa.VARCHAR(), nullable=True),
    sa.Column('cargo', sa.VARCHAR(), nullable=True),
    sa.Column('estado', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_nombre'), 'personal', ['nombre'], unique=False)
    op.create_index(op.f('ix_personal_id'), 'personal', ['id'], unique=False)
    op.create_index(op.f('ix_personal_dni'), 'personal', ['dni'], unique=1)
    op.create_index(op.f('ix_personal_apellido'), 'personal', ['apellido'], unique=False)
    op.drop_index(op.f('ix_users_nombre'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_dni'), table_name='users')
    op.drop_index(op.f('ix_users_apellido'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###